filebeat.inputs:
  - paths:
      - '/usr/share/filebeat/logs/*.log'
    fields_under_root: true
    fields:
      tags: ['json']

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
  indices:
    - index: "warning-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.contains:
        message: "WARN"
